---
- hosts: all
  become: true
  
  tasks:
    # Ansible için apt yerine aptitude tercih ediliyor
    - name: Install aptitude
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    
    # Docker kurulumu için gerekli olan packagelar
    - name: Install system packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - apt-transport-https 
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools

    - name: Add Docker Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Apt sourcelarına docker reposunu ekliyoruz
    - name: Add Docker Repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    # docker-ce kurulumundan önce bir de apt update yapıyoruz
    - name: Install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Python Docker Module
      pip:
        name: docker

    # Docker image'ını çekmek için
    - name: Pull Docker image
      docker_image:
        name: "ubuntu"
        source: pull
   
    # Son olarak container'i yaratiyoruz ve bitti 
    - name: Create the container
      docker_container:
        name: "ansible-remote-install"
        image: "ubuntu"
        command: "sleep 1d"
        state: present
